### PR TITLE
Add a contributing page

### PR DESCRIPTION
**Pull request by stof**
Here is the initial work on #35

### CODE REVIEW

**Comment by stof** [comment]
@aik099 here is the next step needing a review

**Comment by stof** [comment]
@aik099 have you review this one already ?

**Comment by aik099** [comment]
Done now.

What about incorporating https://github.com/minkphp/Mink/blob/master/CONTRIBUTING.md page content here and then Mink and each driver repo will have CONTRIBUTING.md file which points to this central page in docs?

**Comment by stof** [comment]
I will merge this PR as is, given the time it is pending here. Feel free to send another PR to expand the page.

**Pull request merged**
