### PR TITLE
Adding note to install xcode to use zombie.js

### PR DESCRIPTION
**Pull request by nahakiole**
On Mac you need to have Xcode installed for zombie.js to work.
I hope the format of the docs is ok. Is there any way to preview how it will render?

### CODE REVIEW

**Comment by aik099** [comment]
Are you sure?

To run Zombie on Mac I needed to install NodeJS, because the only way to install Zombie is through NPM.

**Comment by nahakiole** [comment]
Do you have Xcode already installed on your maschine? If I try to install Zombie.js through npm I get the following error:
```
> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/zombie/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node

> bufferutil@1.2.1 install /usr/local/lib/node_modules/zombie/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
zombie@4.2.1 /usr/local/lib/node_modules/zombie
├── ms@0.7.1
├── mime@1.3.4
├── debug@2.2.0
├── tough-cookie@2.2.1
├── iconv-lite@0.4.13
├── bluebird@3.2.1
├── eventsource@0.1.6 (original@1.0.0)
├── request@2.69.0 (aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.4.2, oauth-sign@0.8.1, is-typedarray@1.0.0, caseless@0.11.0, stringstream@0.0.5, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, node-uuid@1.4.7, qs@6.0.2, combined-stream@1.0.5, mime-types@2.1.9, form-data@1.0.0-rc3, aws4@1.2.1, bl@1.0.1, hawk@3.1.3, http-signature@1.1.1, har-validator@2.0.6)
```

**Comment by aik099** [comment]
Ah, npm tries to use C compiler to build Zombie modules and compiler is only installed by Xcode.

You're absolutely right then. Thanks for explaining that in detail.

**Comment by stof** [comment]
I would rather link to the zombie.js doc about installation instructions instead of maintaining one on our own (it is the job of Zombie to document how to install Zombie)

**Comment by aik099** [comment]
@nahakiole , I agree with @stof on this one. Please send PR to https://github.com/assaf/zombie with README file update, where installation instructions are.

Closing.

**Pull request closed without merging**
